---
cores: 24 # reduced
latency-wait: 60 #increase latency wait
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times: 2
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
max-jobs-per-second: 10                 #Maximal number of cluster/drmaa jobs per second, default is 10, fractions allowed.
max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
jobs: 500                              #Use at most N CPU cluster/cloud jobs in parallel.
cluster: "sbatch --account=pawsey0012 --partition={resources.partition} --error=${MYSCRATCH}/chiara_snakemake/logs/%j.%x.err --output=${MYSCRATCH}/chiara_snakemake/logs/%j.%x.out --no-requeue --mem={resources.mem_mb} --time={resources.runtime} --ncpus={threads} --cpus-per-task={threads} --ntasks=1"
# For some reason time needs quotes to be read by snakemake
default-resources:
  - runtime=360 #(mins)
  - mem_mb=90000
  - partition=work
# Job resources
set-resources:
  - map_short_reads_giraffe:runtime=720
  - map_short_reads_giraffe:mem_mb=100000
  - count_kmer_in_reads:mem_mb=100000
  - count_kmer_in_reads:runtime=30
  - vgcall:mem_mb=180000
  - vgcall:runtime=60
  - realign_bam:runtime=420
  - realign_bam:mem_mb=64000
  - sample_haplotypes:runtime=30
  - sample_haplotypes:mem_mb=80000
  - index_distance:runtime=60
  - index_distance:mem_mb=90000
  - index_minimizer:runtime=20
  - sv_call_manta:runtime=120
  - sv_call_manta:mem_mb=36000
  - extract_unmapped_reads:mem_mb=16000
  - pack:runtime=120
  - surject_reads_tmp:runtime=960
  - surject_reads_tmp:mem_mb=100000
  - index_bam_tmp:mem_mb=2000
  - index_bam_tmp:runtime=30
  - index_bam:mem_mb=4000
  - index_bam:runtime=30
  - prepare_target_regions:mem_mb=34000
  - prepare_target_regions:runtime=30
  - coverage_mosdepth:mem_mb=20000
  - coverage_mosdepth:runtime=60
  - dv_make_examples:runtime=480
  - dv_make_examples:mem_mb=100000
  - dv_call_variants:runtime=540
  - dv_call_variants:mem_mb=60000

set-threads:
  - sample_haplotypes=16
  - realign_bam=32
  - sv_call_manta=24
  - map_short_reads_giraffe=64
  - vgcall=16
  - surject_reads_tmp=64
  - coverage_mosdepth=8
  - dv_make_examples=48
  - dv_call_variants=16
  - pack=32
  - index_bam=4
  - index_bam_tmp=4
